myshop/cart/urls.py
from django.conf.urls import url
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    # url(r'^adicionar/(?P<product_slug>[-\w]+)/$', views.adicionar_carrinho, name="adicionar_carrinho"),
    url(r'^atualizar/$', views.atualizar_carrinho, name="atualizar_carrinho"),
    url(r'^adicionar/$', views.adicionar_carrinho, name="adicionar_carrinho"),
    url(r'^$', views.mostrar_carrinho, name="mostrar_carrinho"),
    #url(r'^carrinho/delete/(?P<pk>\d+)/$', views.ItemDelete.as_view(), name='cart_item_delete'),
    url(r'^carrinho/deleteall/$', views.delete_all_items, name='cart_delete_allitems'),
    url(r'^carrinho/delete/(?P<pk>\d+)/$', views.delete_item, name='cart_item_delete'),


]

myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^shop/', include('shop.urls', namespace='shop')),

    #url(r'^', include('registration.backends.simple.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

myshop/shop/urls.py
from django.conf.urls import url
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from . import views


from django.contrib.auth.views import (
    password_change,
    password_change_done,
)

urlpatterns = [

    # edit user profile
    url(r'^edit/$', views.edit, name='edit'),

    # user registration
    url(r'^register/$', views.register, name='register'),

    # restore password urls
    url(r'^password-reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'shop:password_reset_done'},
        name='password_reset'),

    url(r'^password-reset/done/$','django.contrib.auth.views.password_reset_done', name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'shop:password_reset_complete'},
        name='password_reset_confirm'),

    url(r'^password-reset/complete/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    url(r'^password-change/$',
        'django.contrib.auth.views.password_change',
        { 'post_change_redirect': 'shop:password_change_done'},
        name='password_change'),
    url(r'^password-change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),


    # para login
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^loggedout/$', 'django.contrib.auth.views.logout', name='loggedout'),
    url(r'^logout-then-login/$', 'django.contrib.auth.views.logout_then_login', name='logout_then_login'),

    # show orders list
    url(r'^orderlist/$', views.order_list, name='order_list'),

    # products
    url(r'^product/(?P<product_slug>[-\w]+)/$', views.product_details, name='product_details'),
    url(r'^$', views.product_list, name="product_list"),
    url(r'^(?P<sub_category_slug>[-\w]+)/$', views.product_list, name='product_list_by_subcategory'),



]

myshop/cart/models.py
#django imports
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.conf import settings
from django.core.urlresolvers import reverse

#local imports
from shop.models import Produto


class Carrinho(models.Model):
    utilizador = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    total = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)

    def get_total_items(self):
        total = 0
        return total

    def __str__(self):
        return str(self.id)

    def valor_total_carrinho(self):
        result = sum(itens.produto.preco * itens.quantidade for itens in self.item_set.all())
        self.total = result


class Item(models.Model):

    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, null=True)
    carrinho = models.ForeignKey(Carrinho, on_delete=models.CASCADE, null=True)
    quantidade = models.PositiveIntegerField()

    # para garantir que o item não se repete no mesmo carrinho
    class Meta:
        unique_together = ('produto', 'carrinho')

    def __str__(self):
        return self.produto.nome

    def get_total_price(self):
        return self.produto.preco * self.quantidade



#Possiveis Signals

# @receiver(post_save, sender=Item, dispatch_uid="update_total_cart")
# def update_total(sender, instance, **kwargs):
#     instance.carrinho.valor_total_carrinho()
#
#     post_save.disconnect(sender=Item)
#     instance.carrinho.save()
#     post_save.connect(update_total, sender=Item)


# @receiver(post_delete, sender=Item, dispatch_uid="update_total_cart_delete")
# def update_total_delete(sender, instance, **kwargs):
#
#     carrinho = instance.carrinho
#     itens = Item.objects.filter(carrinho=carrinho)
#     total = sum(i.produto.preco * i.quantidade for i in itens)
#     instance.carrinho.total = total
#
#     post_delete.disconnect(sender=Item)
#     instance.carrinho.save()
#     post_delete.connect(update_total_delete, sender=Item)

myshop/cart/views.py
#global imports
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.generic import DeleteView


#local imports
from shop.models import Produto
from .models import Carrinho, Item


# class ItemDelete(DeleteView):
#     model = Item
#     success_url = '/carrinho'
    #pk_url_kwarg = "id"

def delete_item(request, pk):
    try:

        item = Item.objects.get(id=pk)
        item.delete()

        utilizador = request.user
        carrinho = Carrinho.objects.filter(utilizador=utilizador).last()
        itens = Item.objects.filter(carrinho=carrinho)
        total = sum(i.produto.preco * i.quantidade for i in itens)
        carrinho.total = total
        carrinho.save()

    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("cart:mostrar_carrinho"))
    return HttpResponseRedirect(reverse("cart:mostrar_carrinho"))


def delete_all_items(request):
    try:

        item = Item.objects.all()
        item.delete()

        utilizador = request.user
        carrinho = Carrinho.objects.filter(utilizador=utilizador).last()
        itens = Item.objects.filter(carrinho=carrinho)
        total = sum(i.produto.preco * i.quantidade for i in itens)
        carrinho.total = total
        carrinho.save()

    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("cart:mostrar_carrinho"))
    return HttpResponseRedirect(reverse("cart:mostrar_carrinho"))


def adicionar_carrinho(request):
    slug = request.POST.get('slug', '')
    quantity = request.POST.get("quantity", "")

    if request.method == 'POST':
        produto = get_object_or_404(Produto, slug=slug)

        if quantity == '':
            return render(request, 'shop/produto/details.html', {'produto': produto, 'erro_stock': 1})
        elif int(quantity) < 1 or produto.stock<int(quantity):
            return render(request, 'shop/produto/details.html', {'produto': produto, 'erro_stock': 1})

        # Pesquisar por utilizador
        utilizador = request.user

        # ***** Filtrar carrinho por user, se não existir criar
        if Carrinho.objects.filter(utilizador=utilizador):
            carrinho = Carrinho.objects.filter(utilizador=utilizador).last()
        else:
            carrinho = Carrinho(utilizador= utilizador)
            carrinho.save()


        # Com o carrinho verificar se existem o item dentro do carrinho
        # se existir aumenta a quantidade
        # cc Cria o item e adiciona ao carrinho
        item_repetido = Item.objects.filter(carrinho=carrinho, produto=produto).first()
        if not item_repetido:
            # Criar novo Item
            item = Item(
                produto=produto,
                quantidade=quantity,
                carrinho=carrinho
            )
            item.save()
        else:
            # Update Item
            item_repetido.quantidade += int(quantity)
            item_repetido.save()
            # return render(request, 'cart/cart.html')



        itens = Item.objects.filter(carrinho=carrinho)
        total = sum(i.produto.preco * i.quantidade for i in itens)
        carrinho.total = total
        carrinho.save()

        return mostrar_carrinho(request)






        # return render(request, 'cart/cart.html', {'produto': produto})


def mostrar_carrinho(request):

    utilizador = request.user

    # ***** Filtrar carrinho por user, se não existir criar
    if Carrinho.objects.filter(utilizador=utilizador):
        carrinho = Carrinho.objects.filter(utilizador=utilizador).last()
    else:
        carrinho = Carrinho(utilizador=utilizador)
        carrinho.save()

    #itens = Item.objects.filter(carrinho = carrinho).select_related('produto')
    itens = Item.objects.filter(carrinho=carrinho)

    # total = sum(i.produto.preco*i.quantidade for i in itens)
    total = carrinho.total

    #item = Item.objects.filter(item=id_produto).first()

    return render(request, 'cart/cart.html', {'itens': itens, 'total': total, })


def atualizar_carrinho(request):
    slug = request.POST.get('slug', '')
    quantity = request.POST.get("quantity", "")
    # slug = request.GET.get('slug')
    # quantity = request.GET.get("quantity")
    erro_stock = 0


    if request.method == 'POST':
        produto = get_object_or_404(Produto, slug=slug)

        # Pesquisar por utilizador
        utilizador = request.user

        # ***** Filtrar carrinho por user, se não existir criar
        if Carrinho.objects.filter(utilizador=utilizador):
            carrinho = Carrinho.objects.filter(utilizador=utilizador).last()
        else:
            carrinho = Carrinho(utilizador= utilizador)
            carrinho.save()

        itens = Item.objects.filter(carrinho=carrinho)
        item_repetido = Item.objects.filter(carrinho=carrinho, produto=produto).first()

        # Update Item
        if produto.stock >= int(quantity) and int(quantity)>0:
            item_repetido.quantidade = int(quantity)
            item_repetido.save()


            total = sum(i.produto.preco * i.quantidade for i in itens)
            carrinho.total = total
            carrinho.save()

            erro_stock = 0

            # answer = ""
            # data = {
            #     'respond': answer,
            #     'quantity': quantity,
            # }
            # return JsonResponse(data)
        else:
            erro_stock = 1
            total = carrinho.total
            # answer = "Valor Superior ao Stock Existente"
            # data = {
            #     'respond': answer,
            #     'quantity': quantity,
            # }
            # return JsonResponse(data)


    return render(request, 'cart/cart.html', {'itens': itens, 'total': total, 'erro_stock': erro_stock })

myshop/cart/templates/cart/cart.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
    {% if erro_stock == 1 %}
        <span style="color: red; float:left" id="alert_quantity">
            <script>
                alert("Erro na selecção de quantidade (quantidade > 0 e quantidade <= stock)")
            </script>
        </span>
    {% endif %}
    <h1>Carrinho</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
            {% for i in itens %}
                <tr>
                    <td>
                        <a href="{{ i.produto.get_absolute_url }}">
                            <img src="{% if i.produto.imagem %}{{ i.produto.imagem.url}}{% else %}{% static "shop/img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ i.produto.nome }}</td>
                    <td>
                        <form id='updateform' action='{% url "cart:atualizar_carrinho" %}' method="post">
                            {% csrf_token %}
                            <input style="width:10%" type="number" name="quantity" value="0" id="produto_quantity"/>
                            <input type="hidden" value="{{ i.produto.nome }}" id="produto_nome"/>
                            <input type="hidden" name="slug" value="{{ i.produto.slug }}" id="produto_slug"/>
                            <input type="submit" value="Atualizar" />
                        </form>

                    </td>


                    <td id="quantidade_ajax">{{ i.quantidade }}</td>

                    <td><a href="{% url "cart:cart_item_delete" i.id%}">Remove</a></td>
                    <td id="produto_preco">{{ i.produto.preco }}</td>
                    <td id="preco_total">{{ i.get_total_price }}</td>

                </tr>
            {% endfor %}
            <tr>
                <td></td><td></td><td></td><td></td><td>Total: </td><td>{{ total }}</td>
            </tr>




        </tbody>

    </table>


    <p class="text-right">

        {# Se o valor total for zero, botão Esvaziar Carrinho e Finalizar Compra deixam de existir    #}
        {% if total != 0 %}
            {% if erro_stock == 1 %}

            {% else %}
                <a href="{% url "cart:cart_delete_allitems" %}" class="button light">Esvaziar Carrinho</a>
                <a href="{% url "orders:order_create" %}" class="button">Finalizar Compra</a>
            {% endif %}
        {% endif %}

        <a href="{% url "shop:product_list" %}" class="button light">Comprar mais!</a>

    </p>

{#    <script>#}
{#            $(document).ready(function(){#}
{#                $("#updateform").on('submit', function (e) {#}
{#                        e.preventDefault();#}
{#                        var quantity = $("#produto_quantity").val();#}
{#                        var nome = $("#produto_nome").val();#}
{#                        var slug = $("#produto_slug").val();#}
{#                        //var input = $(this).serialize()#}
{##}
{#                        $.ajax({#}
{#                            url: '{% url 'cart:atualizar_carrinho' %}',#}
{#                            data: {#}
{#                              'quantity': quantity,#}
{#                                'nome': nome,#}
{#                                'slug':slug,#}
{#                            },#}
{#                            dataType: 'json',#}
{#                            success: function (data) {#}
{#                              document.getElementById('alert_quantity').innerHTML = data['respond'];#}
{#                              document.getElementById('quantidade_ajax').innerHTML = data['quantity'];#}
{##}
{#                            }#}
{#                          });#}
{#                        });#}
{#            })#}
{#    </script>#}

{% endblock %}